runtime: java
env: flex

#runtime_config:  # Optional
#  jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored

health_check:
  enable_health_check: False

manual_scaling:
  instances: 1

endpoints_api_service:
  name: "workorder-ri.appspot.com"
  config_id: "2017-06-28r2"
